### ISSUE TITLE
Upgrade the IfcOpenShell / BlenderBIM Add-on websites

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/website#2]
Although it's necessary for us to keep on hacking away on the code, it's also necessary to provide a better web presence. Ideally, someone (hey, is that someone **you**? :) will take charge of the IfcOpenShell and BlenderBIM Add-on website :) This involves graphic design, creating interesting screenshots, coming up with engaging code samples (or the idea of them, we'll write the code!), writing HTML / CSS / JS, taking a critical look at what content users want to see, and basically all the usual stuff involved in building and maintaining a website.

The website will be static content. No user sign ups and so on so don't worry about backend. We can also provide and help manage servers / domains / ssl.

Note that a lot of content may be delegated to a dedicated documentation website (after all most visitors are devs or powerusers) so the actual pages for the site will be quite minimal, but we hope quite visually engaging and has the necessary calls to action for visitors (e.g. go to docs, ask for help on forums, download via this link, etc).

Nothing is set is stone, so as is with most FOSS projects, the one who implements, decides :)

Current sites: http://ifcopenshell.org (dev-focused lib/engine/cli apps) https://blenderbim.org (user focused blender-based gui)

 1. Redesign both websites to have a common look and feel as they are part of the same umbrella.
 2. The design should be modern and beautiful :)
 3. It must be very clear for a new IfcOpenShell user to discover what makes it special
 4. It must be very clear for a new BlenderBIM Add-on user to discover what it is and what its features are
 5. A C++ user should be able to quickly be able to write and compile their first Hello World
 6. A Python user should be able to quickly write their first hello world, including exposure to the utils and api, some of IfcOpenShell's key scripting strengths
 7. It should be clear what all the utils are for IfcOpenShell (IfcClash, IfcDiff, IfcCSV, etc)
 8. All documentation must have a cohesive template design and standardised structure
 9. All CLI utils must have clear CLI running instructions
 10. Basic guides should be written for common BlenderBIM GUI tasks (view, create new, common editing things)
 11. User should readily identify how to contribute
 12. User should readily identify how to ask for help through different mediums (bugs, forum, chat, paid private consultation, etc)
 13. Fundraising should be prominent in key parts of the site (e.g. blenderbim download) to encourage raising funds towards goals, with clear vision of results of funding communicated to users
 14. IfcOpenShell and BlenderBIM Add-on to direct all funding towards OpenSourceBIM OpenCollective.
 15. OpenSourceBIM OpenCollective page to be updated with new text, goals, tiers, graphics, etc
 16. The continuous confusion of "how do i install IfcOpenShell" needs to be solved :) Pip? Conda? Custom download? Compile?
 17. Compilation instructions for C++ may perhaps be migrated to sphinx docs and reviewed to make sure it is up to date, especially on platforms where common bugs crop up (Mac? latest visual studio I've noticed?)

**Comment by aothms** [comment]
Note that the actual website was also quickly upgraded awaiting finalized mocks http://ifcopenshell.org/ 

The things @Moult and I were discussing in private in terms of graphics is that I find the "ears" in the page margin a bit too pronounced and looking for ways for them to emphasize more the text and structure. If anyone has ideas on balancing graphical boldness with a more background role for the decoration we're curious to hear some ideas.

![afbeelding](https://user-images.githubusercontent.com/1096535/169761056-f1b448c5-03db-488c-a8cf-45d586d7c07e.png)

![afbeelding](https://user-images.githubusercontent.com/1096535/169761172-f940e952-c5e5-42c5-a458-9e67ea69c42c.png)

**Comment by pag0dy** [comment]
I love what you've done with some of the graphics I provided, the mockups look awesome. 

I would like to make a suggestion if I may. In my experience, the website's design and coding parts would be easier to approach and would evolve faster if they were looked at as separate jobs and probably for at least two different people.  They both can take some time but could be developed in parallel. 

I know it could be harder to find two people that commit to the project, than just one. But on the other side, once the site is designed, practically anyone can make small contributions to the code. At least for me, the design part was what took most of my time (not being a professional designer).

**Comment by Moult** [comment]
@pag0dy thank _you_ for the excellent work you did! I totally agree that design and coding should be separate tasks. Design and site structure are more tightly connected, whereas coding can indeed be a distinct task. Hopefully now that the mockups are slowly maturing, someone can help with the slicing and mobile friendliness.

As per @aothms suggestion the new IfcConvert logo is updated:

![2022-05-28-093539_96x146_scrot](https://user-images.githubusercontent.com/88302/170800935-2898a7be-f66a-42ef-b3a4-df41f7fd0536.png)

I found some spare time to draw up a few more graphics and try out a style minus the "ears" :)

I wonder if we can begin reaching out to companies who will help sponsor OpenSourceBIM's collective and we can put their logo up on the page :) @aothms perhaps your university? I can reach out to my employer and perhaps a few others?

![Page 2](https://user-images.githubusercontent.com/88302/170800915-21d2c034-9f5c-41bd-9a3f-9559d0733fac.png)
![Page 5](https://user-images.githubusercontent.com/88302/170800917-8dc6c227-7f70-40c8-abd1-f09a955d146f.png)

**Comment by Moult** [comment]
@chunchk indeed, the existing site actually doesn't really have a colour scheme. It's just grey plus a red/beige/earthy highlight. The idea is to express the tight connection between the BlenderBIM Add-on which is effectively a user facing frontend to IfcOpenShell's capabilities and ecosystem and grew out of the original IfcBlender.

**Comment by jamilu-jibrilla** [comment]
Hello
I want to help out with coding the designs but i am kind of lost, is there a file that has all the designs i would be working with? 
Also, i  saw some mockup's above but i am not sure where to start from as they are not arranged.

**Comment by Moult** [comment]
@jamilu-jibrilla hey there! The file which contains all the designs is https://github.com/IfcOpenShell/website/blob/main/wip-design/mockup.svg - you need to open it with the latest version of Inkscape, which supports multipage SVGs. One SVG page per webpage. It's a very small website, there are only a few pages acting as a poster for various things :) Does that make sense?

**Comment by rfdiazpr** [comment]
@jamilu-jibrilla I would like to join you on this undertaking.

**Comment by Moult** [comment]
@rfdiazpr that would be great! The code is all frontend, so if you wish to steal any markup from http://ifcopenshell.org/ go right ahead :) But also feel free to treat it as a fresh project if that's easier. As you can see, there are only a few pages to create (5? 6?) across both domains (ifcopenshell.org and blenderbim.org) the rest are all to link to external sites like Github, or the autogenerated Sphinx docs.

**Comment by jamilu-jibrilla** [comment]
@rfdiazpr sorry for the late reply. 
Is there some way we can communicate? 
so we won't be working on the same stuff.

**Comment by rfdiazpr** [comment]
> @rfdiazpr sorry for the late reply. Is there some way we can communicate? so we won't be working on the same stuff.

@jamilu-jibrilla I emailed you my contact information.

**Comment by Moult** [comment]
@jamilu-jibrilla @rfdiazpr hey how'd it go did either of you manage to start writing any code? Can we help in any way?

**Comment by rfdiazpr** [comment]
@Moult Yes, working with the blenderbim.

**Comment by jamilu-jibrilla** [comment]
@Moult hello, 
we are working together. I'll let you know if anything comes up. Thanks.

**Comment by Moult** [comment]
@jamilu-jibrilla @rfdiazpr might it make sense to fork/commit to this/a repo so we can help? :)

**Comment by rfdiazpr** [comment]
@Moult Yes. I forked the repo, working offline, but will eventually commit the changes.

**Comment by Moult** [comment]
@jamilu-jibrilla @rfdiazpr bump :)

**Comment by jamilu-jibrilla** [comment]
@Moult heyy, sorry for not updating you on how things are going. I am currently working on the last design of the IfcOpenShell page. I also try to tweak it to make it responsive on mobile devices. @rfdiazpr and i would have something for you in a day or two.

**Comment by Moult** [comment]
Awesome! I'm so excited!

**Comment by Moult** [comment]
To make it responsive, might I recommend that you use a CSS 12-column grid-based template? This would make it "automatically" responsive without needing to do any extra work.

**Comment by jamilu-jibrilla** [comment]
Oh okay......Thanks!!
I would try implementing it that way.

**Comment by dirkolbrich** [comment]
Hey, I did play a bit with the website too. Even though I'm not far into the game you maybe want to check out the WIP.

I set up a dummy website structure (responsive layout, static pages, blog for `.md`, `rst` and `.ipynb` files) using the [Nikola](getnikola.com) static site generator and [TailwindCSS](https://tailwindcss.com) framework. Head over to my [fork](https://github.com/dirkolbrich/ifcopenshell-org/tree/redesign-v2) and build the site locally.

For the design I started to transfer the mockup pages using [Penpot.app](https://penpot.app) to maybe open it up for collaboration. You can see the WIP sites [here](https://design.penpot.app/#/view/a4c36b20-35b0-11ed-a332-c67f7655c7b3?page-id=12724fb0-37f5-11ed-8a12-19fbbcc10a0e&section=interactions&index=0&share-id=980f38c0-3a81-11ed-a5c2-cf2300df1f4f).

**Comment by aothms** [comment]
@dirkolbrich https://academy.ifcopenshell.org/ also uses Nikola https://github.com/IfcOpenShell/academy/

Hope you all find a way to collaborate, and maybe consider the academy as well in those plans

**Comment by Moult** [comment]
@dirkolbrich hey hey, awesome stuff! Just confirming you've seen https://github.com/IfcOpenShell/website/issues/2#issuecomment-1235550141 ? All the design is already in SVG and source files are available (requires latest version of Inkscape which supports multipage content). That said, apart from the vector art, everything should be able to be recreated in pure CSS.

Apologies if you already were using that SVG, I might've made the wrong assumptions when I read "started to transfer the mockup pages using Penpot".

**Comment by dirkolbrich** [comment]
@aothms Yes, I saw the academy repo with 13 posts as well as the blog with 22 posts. I would suggest to bundle the blog posts and the academy articles under one common "blog / articles" sub section within the website. Both are not that many and are currently scattered across different subdomains thus not easily findable by interested visitors. 
The `/posts` subfolder could even get a nice index page, which gives an intro and distinguishes between the blog and educational academy articles, makes the searchable by tags etc.
Could you provide the exported blog articles from Blogger (maybe in a separate emptied branch in this repo), so I can try out a setup together with the academy articles?

**Comment by aothms** [comment]
It looks like I can get a XML dump. Does that help?
[ifcopenshell-blog-09-23-2022.xml.txt](https://github.com/IfcOpenShell/website/files/9631994/ifcopenshell-blog-09-23-2022.xml.txt)

**Comment by dirkolbrich** [comment]
@Moult Yes, I'm already using the `mockup.svg` from this repo. It's a good start and concept, but IMHO it needs more work to be a complete design to hand off to coding. Visual appearance in different screen sizes (responsive), color and font specification etc. 
I thought bringing this to a Penpot team workspace could accelerate collaboration. Anyone who is interested can request an invasion link to the team. I tried to import the complete SVG, but Penpot struggles a bit with this, so it's a rebuild piece by piece.

**Comment by dirkolbrich** [comment]
> It looks like I can get a XML dump. Does that help?
> [ifcopenshell-blog-09-23-2022.xml.txt](https://github.com/IfcOpenShell/website/files/9631994/ifcopenshell-blog-09-23-2022.xml.txt)
Actually no, but thanks. It's HTML escaped including all the comments. Untangling this is beyond my knowledge. I think scraping and images from the Blogger site is faster for me.

**Comment by Moult** [comment]
@dirkolbrich everything there should be possible on standard CSS including fonts colours and grid (and said grid should offer a natural mobile option). I used to be a web developer so it was designed with that in mind :)

**Comment by dirkolbrich** [comment]
@Moult sorry, didn't wanted to question or diminish your experience. Let's just agree that we may have a different understanding of what a concept and what a design is, without judging these.

**Comment by jamilu-jibrilla** [comment]
@Moult This is a demo of the IfcOpenShell website, please review. [Link](https://jamilu-jibrilla.github.io/IfcOpenShell-Demo/index.html)

**Comment by Moult** [comment]
@jamilu-jibrilla Awesome work! There seems to be a few minor issues:

 - SVG graphics seem to be stretched / blurry (why not keep them as SVGs?)
 - Font should be [Nunito](https://fonts.google.com/specimen/Nunito)
 - Center alignment seems to be off (see screenshot) and clipping of the feature image
 - Body font colour should be 2e3436, footer text is 888a85 with babdb6 horizontal rule
 - Body bg colour eeeeec with f7f7f6 for header bar
 - Some alignments / proportions seem to be off: see image below. It roughly follows a standard 12-column layout with a bit of variation on "featured" sections like the main blurb and so on. The column margins are used as a standard margin/padding throughout. See the annotated mockup of the relationship of margins

![2022-09-24-161205_763x542_scrot](https://user-images.githubusercontent.com/88302/192082970-5c692311-0ae1-4f80-a89e-833dbe7c6a2d.png)

Here's what it looks like on my screen:

![2022-09-24-155911_1920x1080_scrot](https://user-images.githubusercontent.com/88302/192082975-ba8daa9a-ab0e-4af8-ace6-efb6fd3c39c0.png)

Great work on the responsive interpretation (yes, I know this is old-school and not mobile-first,  :) ) it looks great!

![2022-09-24-161423_470x774_scrot](https://user-images.githubusercontent.com/88302/192083004-cb35862f-def0-4d21-b812-ba646d01066b.png)
![2022-09-24-161344_476x790_scrot](https://user-images.githubusercontent.com/88302/192083006-7d693560-f2ac-4cdd-8c81-11315e48b410.png)

**Comment by jamilu-jibrilla** [comment]
Alright, I'll work on it. 
Thanks for the feedback. 🙏

**Comment by rfdiazpr** [comment]
@Moult This is a first draft for comments -> [Link](https://rfdiazpr.github.io/blenderbimsite-demo/index.html)

**Comment by Moult** [comment]
@rfdiazpr hey there, it's a good start, but it seems to lack some of the faetures of @jamilu-jibrilla and look less like the design intent. Perhaps it's best  to work together?

**Comment by jamilu-jibrilla** [comment]
@Moult sorry this is taking long. i don't always have access to a computer, but i try to work on it whenever i do.
i made some changes based on your review, can you go through the site again, also check out the other pages (products, community). [Link](https://jamilu-jibrilla.github.io/IfcOpenShell-Demo/index.html)

**Comment by jamilu-jibrilla** [comment]
Hello @Moult
I haven't heard back from you, please review the site and let me know if i can a create a pull request.

**Comment by Moult** [comment]
@jamilu-jibrilla thank you so much! You've really helped! Do you have a github source code link by any chance?

**Comment by jamilu-jibrilla** [comment]
@Moult yes, this is the link to the github repository.
[https://github.com/jamilu-jibrilla/IfcOpenShell-Demo](https://github.com/jamilu-jibrilla/IfcOpenShell-Demo)

**Comment by jamilu-jibrilla** [comment]
If you are okay with the site, i can fork and push the files to this repository.

**Comment by Moult** [comment]
I think it's an excellent start! You've really helped and I think we can take it from here :) I think the Github repo should be sufficient to play with the code. Thank you so much @jamilu-jibrilla !
