### ISSUE TITLE
https://ifcopenshell.org/ - SSL do not work - Error 502

### ISSUE THREAD

**Issue by Mannshoch** [IfcOpenShell/website#3]
**_https_** ://ifcopenshell.org/ 

SSL do not work - Error 502

**Comment by Mannshoch** [comment]
ping

**Comment by Mannshoch** [comment]
Ping @aothms

**Comment by aothms** [comment]
There are several redesign and rework attempts for the website. Tackling
ssl separately doesn't have highest priority.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op ma 29 aug. 2022 15:46 schreef Mannshoch ***@***.***>:

**Comment by Mannshoch** [comment]
I got Feedback from Windows Users, that Microsoft Edge only show a 502. It seems this user could not open this website without ssl. Even they try to remove s from https in the URL.

**Comment by aothms** [comment]
Can't reproduce that

![Uploading afbeelding.png…]()

**Comment by Mannshoch** [comment]
His coworker has the same Problem. I assume there is a group policy that do that. Couldn't you get a Let's encrypt Certificate?

**Comment by Moult** [comment]
Closing because https works now.
